language: ruby
before_install:
  - gem install rake -v '>= 10.3.2'
before_script:
  - mysql -e 'create database TurboRango_test;'
  - RAILS_ENV=test rake --trace db:migrate
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.2
notifications:
  email:
    - johnvoloski@gmail.com
